services:
  - type: web
    name: telegram-trading-bot
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: trading-bot-db
          property: connectionString
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: BINANCE_API_KEY
        sync: false
      - key: BINANCE_SECRET_KEY
        sync: false
      - key: OANDA_API_KEY
        sync: false
      - key: OANDA_ACCOUNT_ID
        sync: false
      - key: ENVIRONMENT
        value: production

databases:
  - name: trading-bot-db
    databaseName: trading_bot
    user: trading_bot_user
